In [1]:
import pandas as pd
df=pd.read_csv('E:\\annual-enterprise-survey-2019-financial-year-provisional-csv.csv',header=3)
df

,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"35,250",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"7,458",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"20,977",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
32437,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32438,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32439,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [2]:
df.head()

,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"35,250",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"7,458",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"20,977",ANZSIC06 divisions A-S (excluding classes K633...

In [3]:
df.head(2)

,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...

In [4]:
df.tail(2)

,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [6]:
df=pd.read_csv('E:\\annual-enterprise-survey-2019-financial-year-provisional-csv.csv',header=6)
df

,2019,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"35,250","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2019,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"7,458",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"20,977",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"112,960",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,206,ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"1,767",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
32434,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32435,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32436,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32437,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32438,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [7]:
df.head()

,2019,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"35,250","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2019,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"7,458",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"20,977",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"112,960",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,206,ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"1,767",ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
df.